const buttonsAll = {
    'encoderPageHeader': { 'address': 'encoderPage', 'style': 'pageHeader7', 'stylePressed': 'pageHeader7Pressed', 'styleText': 'pageHeader7Text', 'functype': 'pageHeader', 'label': 'Encoders', 'argtype': 'i', 'argvalue': '0' },
    'dsPageHeader': { 'address': 'dsPage', 'style': 'pageHeader7', 'stylePressed': 'pageHeader7Pressed', 'styleText': 'pageHeader7Text', 'functype': 'pageHeader', 'label': 'Direct Selects', 'argtype': 'i', 'argvalue': '0' },
    'faderPageHeader': { 'address': 'faderPage', 'style': 'pageHeader7', 'stylePressed': 'pageHeader7Pressed', 'styleText': 'pageHeader7Text', 'functype': 'pageHeader', 'label': 'Playback', 'argtype': 'i', 'argvalue': '0' },
    'focusPageHeader': { 'address': 'focusPage', 'style': 'pageHeader7', 'stylePressed': 'pageHeader7Pressed', 'styleText': 'pageHeader7Text', 'functype': 'pageHeader', 'label': 'Focus', 'argtype': 'i', 'argvalue': '0' },
    'remotePageHeader': { 'address': 'remotePage', 'style': 'pageHeader7', 'stylePressed': 'pageHeader7Pressed', 'styleText': 'pageHeader7Text', 'functype': 'pageHeader', 'label': 'Remote', 'argtype': 'i', 'argvalue': '0' },
    'facepanelPageHeader': { 'address': 'facepanelPage', 'style': 'pageHeader7', 'stylePressed': 'pageHeader7Pressed', 'styleText': 'pageHeader7Text', 'functype': 'pageHeader', 'label': 'Face Panel', 'argtype': 'i', 'argvalue': '0' },
    'testPageHeader': { 'address': 'testPage', 'style': 'pageHeader7', 'stylePressed': 'pageHeader7Pressed', 'styleText': 'pageHeader7Text', 'functype': 'pageHeader', 'label': 'TEST', 'argtype': 'i', 'argvalue': '0' },
    'console': { 'address': '', 'style': 'console7', 'stylePressed': 'console7Pressed', 'styleText': 'console7Text', 'functype': 'console', 'label': '', 'argtype': 'i', 'argvalue': '0' },
    'consoleInput': { 'address': '', 'style': 'consoleInput7', 'stylePressed': 'consoleInput7Pressed', 'styleText': 'consoleInput7Text', 'functype': 'consoleInput', 'label': '', 'argtype': 'i', 'argvalue': '0' },
    'masterLayout': { 'address': '', 'style': 'masterLayout7', 'stylePressed': 'masterLayout7Pressed', 'styleText': 'masterLayout7Text', 'functype': 'masterLayout', 'label': '', 'argtype': 'i', 'argvalue': '0' },
    'masterLayoutInput': { 'address': '', 'style': 'masterLayoutInput7', 'stylePressed': 'masterLayoutInput7Pressed', 'styleText': 'masterLayoutInput7Text', 'functype': 'masterLayoutInput', 'label': '', 'argtype': 'i', 'argvalue': '0' },
    'layout': { 'address': '', 'style': 'layout7', 'stylePressed': 'layout7Pressed', 'styleText': 'layout7Text', 'functype': 'layout', 'label': '', 'argtype': 'i', 'argvalue': '0' },
    'layoutBtn': { 'address': '', 'style': 'layoutBtn7', 'stylePressed': 'layoutBtn7Pressed', 'styleText': 'layoutBtn7Text', 'functype': 'layoutBtn', 'label': '', 'argtype': 'i', 'argvalue': '0' },
    'minus': { 'address': '/eos/key/-', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': '-', 'argtype': 'i', 'argvalue': '0' },
    'minus_percent': { 'address': '/eos/key/-%', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': '-%', 'argtype': 'i', 'argvalue': '0' },
    'period': { 'address': '/eos/key/.', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': '.', 'argtype': 'i', 'argvalue': '0' },
    'slash': { 'address': '/eos/key/\\', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': '/', 'argtype': 'i', 'argvalue': '0' },
    'plus': { 'address': '/eos/key/+', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': '+', 'argtype': 'i', 'argvalue': '0' },
    'plus_percent': { 'address': '/eos/key/+%', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': '+%', 'argtype': 'i', 'argvalue': '0' },
    '0': { 'address': '/eos/key/0', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': '0', 'argtype': 'i', 'argvalue': '0' },
    '1': { 'address': '/eos/key/1', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': '1', 'argtype': 'i', 'argvalue': '0' },
    '2': { 'address': '/eos/key/2', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': '2', 'argtype': 'i', 'argvalue': '0' },
    '3': { 'address': '/eos/key/3', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': '3', 'argtype': 'i', 'argvalue': '0' },
    '4': { 'address': '/eos/key/4', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': '4', 'argtype': 'i', 'argvalue': '0' },
    '5': { 'address': '/eos/key/5', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': '5', 'argtype': 'i', 'argvalue': '0' },
    '6': { 'address': '/eos/key/6', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': '6', 'argtype': 'i', 'argvalue': '0' },
    '7': { 'address': '/eos/key/7', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': '7', 'argtype': 'i', 'argvalue': '0' },
    '8': { 'address': '/eos/key/8', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': '8', 'argtype': 'i', 'argvalue': '0' },
    '9': { 'address': '/eos/key/9', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': '9', 'argtype': 'i', 'argvalue': '0' },
    '0_black': { 'address': '/eos/key/0', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': '0', 'argtype': 'i', 'argvalue': '0' },
    '1_black': { 'address': '/eos/key/1', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': '1', 'argtype': 'i', 'argvalue': '0' },
    '2_black': { 'address': '/eos/key/2', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': '2', 'argtype': 'i', 'argvalue': '0' },
    '3_black': { 'address': '/eos/key/3', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': '3', 'argtype': 'i', 'argvalue': '0' },
    '4_black': { 'address': '/eos/key/4', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': '4', 'argtype': 'i', 'argvalue': '0' },
    '5_black': { 'address': '/eos/key/5', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': '5', 'argtype': 'i', 'argvalue': '0' },
    '6_black': { 'address': '/eos/key/6', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': '6', 'argtype': 'i', 'argvalue': '0' },
    '7_black': { 'address': '/eos/key/7', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': '7', 'argtype': 'i', 'argvalue': '0' },
    '8_black': { 'address': '/eos/key/8', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': '8', 'argtype': 'i', 'argvalue': '0' },
    '9_black': { 'address': '/eos/key/9', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': '9', 'argtype': 'i', 'argvalue': '0' },
    'minus_black': { 'address': '/eos/key/-', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': '-', 'argtype': 'i', 'argvalue': '0' },
    'plus_black': { 'address': '/eos/key/+', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': '+', 'argtype': 'i', 'argvalue': '0' },
    'period_black': { 'address': '/eos/key/.', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': '.', 'argtype': 'i', 'argvalue': '0' },
    'clear_cmd_black': { 'address': '/eos/key/clear_cmd', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': 'Clear', 'argtype': 'i', 'argvalue': '0' },
    'slash_black': { 'address': '/eos/key/\\', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': '/', 'argtype': 'i', 'argvalue': '0' },
    'level_black': { 'address': '/eos/key/level', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': 'Level', 'argtype': 'i', 'argvalue': '0' },
    'enter_black': { 'address': '/eos/key/enter', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': 'Enter', 'argtype': 'i', 'argvalue': '0' },
    'at_black': { 'address': '/eos/key/at', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': 'At', 'argtype': 'i', 'argvalue': '0' },
    'full_black': { 'address': '/eos/key/full', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': 'Full', 'argtype': 'i', 'argvalue': '0' },
    'sneak_black': { 'address': '/eos/key/sneak', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': 'Sneak', 'argtype': 'i', 'argvalue': '0' },
    'thru_black': { 'address': '/eos/key/thru', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': 'Thru', 'argtype': 'i', 'argvalue': '0' },

    'about': { 'address': '/eos/key/about', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'About', 'argtype': 'i', 'argvalue': '0' },
    'activeChan': { 'address': '/eos/out/active/chan', 'style': 'info7', 'stylePressed': 'info7Pressed', 'styleText': 'info7Text', 'functype': 'info', 'label': 'CHAN SELECTION', 'argtype': 'i', 'argvalue': '0' },
    'address': { 'address': '/eos/key/address', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Address Patch', 'argtype': 'i', 'argvalue': '0' },
    'Arrow_Down': { 'address': '/eos/key/Arrow_Down', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Down Arrow', 'argtype': 'i', 'argvalue': '0' },
    'Arrow_Left': { 'address': '/eos/key/Arrow_Left', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Left Arrow', 'argtype': 'i', 'argvalue': '0' },
    'Arrow_Right': { 'address': '/eos/key/Arrow_Right', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Right Arrow', 'argtype': 'i', 'argvalue': '0' },
    'Arrow_Up': { 'address': '/eos/key/Arrow_Up', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Up Arrow', 'argtype': 'i', 'argvalue': '0' },
    'assert': { 'address': '/eos/key/assert', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': 'Assert', 'argtype': 'i', 'argvalue': '0' },
    'at': { 'address': '/eos/key/at', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'At', 'argtype': 'i', 'argvalue': '0' },
    'beam_palette': { 'address': '/eos/key/beam_palette', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Beam Palette', 'argtype': 'i', 'argvalue': '0' },
    'Blind': { 'address': '/eos/key/Blind', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Blind', 'argtype': 'i', 'argvalue': '0' },
    'block': { 'address': '/eos/key/block', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': 'Block', 'argtype': 'i', 'argvalue': '0' },
    'capture': { 'address': '/eos/key/capture', 'style': 'btn2', 'stylePressed': 'btn2Pressed', 'styleText': 'btn2Text', 'functype': 'btn', 'label': 'Capture', 'argtype': 'i', 'argvalue': '0' },
    'check': { 'address': '/eos/key/check', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Check', 'argtype': 'i', 'argvalue': '0' },
    'clear_cmd': { 'address': '/eos/key/clear_cmd', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': 'Clear', 'argtype': 'i', 'argvalue': '0' },
    'color_palette': { 'address': '/eos/key/color_palette', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Color Palette', 'argtype': 'i', 'argvalue': '0' },

    'copy_to': { 'address': '/eos/key/copy_to', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'CopyTo', 'argtype': 'i', 'argvalue': '0' },
    'cue': { 'address': '/eos/key/cue', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Cue', 'argtype': 'i', 'argvalue': '0' },
    'data': { 'address': '/eos/key/data', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Data', 'argtype': 'i', 'argvalue': '0' },
    'delay': { 'address': '/eos/key/delay', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Delay', 'argtype': 'i', 'argvalue': '0' },
    'delete': { 'address': '/eos/key/delete', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Delete', 'argtype': 'i', 'argvalue': '0' },
    'effect': { 'address': '/eos/key/effect', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Effect', 'argtype': 'i', 'argvalue': '0' },
    'enter': { 'address': '/eos/key/enter', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Enter', 'argtype': 'i', 'argvalue': '0' },
    'Escape': { 'address': '/eos/key/Escape', 'style': 'btn1', 'stylePressed': 'btn1Pressed', 'styleText': 'btn1Text', 'functype': 'btn', 'label': 'Escape', 'argtype': 'i', 'argvalue': '0' },
    'expand': { 'address': '/eos/key/expand', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Expand', 'argtype': 'i', 'argvalue': '0' },
    'fan': { 'address': '/eos/key/fan', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Fan', 'argtype': 'i', 'argvalue': '0' },
    'flash': { 'address': '/eos/key/flash', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Flash', 'argtype': 'i', 'argvalue': '0' },
    'flexichannel_mode': { 'address': '/eos/key/flexichannel_mode', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Flexi', 'argtype': 'i', 'argvalue': '0' },
    'focus_palette': { 'address': '/eos/key/focus_palette', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Focus Palette', 'argtype': 'i', 'argvalue': '0' },
    'format': { 'address': '/eos/key/format', 'style': 'btn4', 'stylePressed': 'btn4Pressed', 'styleText': 'btn4Text', 'functype': 'btn', 'label': 'Format', 'argtype': 'i', 'argvalue': '0' },
    'full': { 'address': '/eos/key/full', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Full', 'argtype': 'i', 'argvalue': '0' },
    'go_to_cue': { 'address': '/eos/key/go_to_cue', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': 'Goto Cue', 'argtype': 'i', 'argvalue': '0' },
    'group': { 'address': '/eos/key/group', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Group', 'argtype': 'i', 'argvalue': '0' },
    'help': { 'address': '/eos/key/help', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Help', 'argtype': 'i', 'argvalue': '0' },
    'highlight': { 'address': '/eos/key/highlight', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Highlight', 'argtype': 'i', 'argvalue': '0' },
    'home': { 'address': '/eos/key/home', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Home', 'argtype': 'i', 'argvalue': '0' },
    'intensity_palette': { 'address': '/eos/key/intensity_palette', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Int Palette', 'argtype': 'i', 'argvalue': '0' },
    'last': { 'address': '/eos/key/last', 'style': 'btn2', 'stylePressed': 'btn2Pressed', 'styleText': 'btn2Text', 'functype': 'btn', 'label': 'Last', 'argtype': 'i', 'argvalue': '0' },
    'learn': { 'address': '/eos/key/learn', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Learn', 'argtype': 'i', 'argvalue': '0' },
    'level': { 'address': '/eos/key/level', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Level', 'argtype': 'i', 'argvalue': '0' },
    'Live': { 'address': '/eos/key/Live', 'style': 'btn4', 'stylePressed': 'btn4Pressed', 'styleText': 'btn4Text', 'functype': 'btn', 'label': 'Live', 'argtype': 'i', 'argvalue': '0' },
    'macro': { 'address': '/eos/key/macro', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Macro', 'argtype': 'i', 'argvalue': '0' },
    'mark': { 'address': '/eos/key/mark', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Mark', 'argtype': 'i', 'argvalue': '0' },
    'more_softkeys': { 'address': '/eos/key/more_softkeys', 'style': 'btn9', 'stylePressed': 'btn9Pressed', 'styleText': 'btn9Text', 'functype': 'btn', 'label': 'More Softkeys', 'argtype': 'i', 'argvalue': '0' },
    'next': { 'address': '/eos/key/next', 'style': 'btn2', 'stylePressed': 'btn2Pressed', 'styleText': 'btn2Text', 'functype': 'btn', 'label': 'Next', 'argtype': 'i', 'argvalue': '0' },
    'out': { 'address': '/eos/key/out', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Out', 'argtype': 'i', 'argvalue': '0' },
    'park': { 'address': '/eos/key/park', 'style': 'btn2', 'stylePressed': 'btn2Pressed', 'styleText': 'btn2Text', 'functype': 'btn', 'label': 'Park', 'argtype': 'i', 'argvalue': '0' },
    'part': { 'address': '/eos/key/part', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Part', 'argtype': 'i', 'argvalue': '0' },
    'path': { 'address': '/eos/key/path', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Path', 'argtype': 'i', 'argvalue': '0' },
    'preset': { 'address': '/eos/key/preset', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Preset', 'argtype': 'i', 'argvalue': '0' },
    'recall_from': { 'address': '/eos/key/recall_from', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': 'Recall From', 'argtype': 'i', 'argvalue': '0' },
    'record': { 'address': '/eos/key/record', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Record', 'argtype': 'i', 'argvalue': '0' },
    'record_only': { 'address': '/eos/key/record_only', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Record Only', 'argtype': 'i', 'argvalue': '0' },
    'rem_dim': { 'address': '/eos/key/rem_dim', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Rem Dim', 'argtype': 'i', 'argvalue': '0' },
    'Select': { 'address': '/eos/key/Select', 'style': 'btn1', 'stylePressed': 'btn1Pressed', 'styleText': 'btn1Text', 'functype': 'btn', 'label': 'Select', 'argtype': 'i', 'argvalue': '0' },
    'select_active': { 'address': '/eos/key/select_active', 'style': 'btn2', 'stylePressed': 'btn2Pressed', 'styleText': 'btn2Text', 'functype': 'btn', 'label': 'Select Active', 'argtype': 'i', 'argvalue': '0' },
    'select_last': { 'address': '/eos/key/select_last', 'style': 'btn2', 'stylePressed': 'btn2Pressed', 'styleText': 'btn2Text', 'functype': 'btn', 'label': 'Select Last', 'argtype': 'i', 'argvalue': '0' },
    'select_manual': { 'address': '/eos/key/select_manual', 'style': 'btn2', 'stylePressed': 'btn2Pressed', 'styleText': 'btn2Text', 'functype': 'btn', 'label': 'Select Manual', 'argtype': 'i', 'argvalue': '0' },
    'shift': { 'address': '/eos/key/shift', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Shift', 'argtype': 'i', 'argvalue': '0' },
    'sneak': { 'address': '/eos/key/sneak', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Sneak', 'argtype': 'i', 'argvalue': '0' },
    'softkey_1': { 'address': '/eos/key/softkey_1', 'style': 'btn9', 'stylePressed': 'btn9Pressed', 'styleText': 'btn9Text', 'functype': 'btn', 'label': 'SoftKey 1', 'argtype': 'i', 'argvalue': '0' },
    'softkey_2': { 'address': '/eos/key/softkey_2', 'style': 'btn9', 'stylePressed': 'btn9Pressed', 'styleText': 'btn9Text', 'functype': 'btn', 'label': 'Softkey 2', 'argtype': 'i', 'argvalue': '0' },
    'softkey_3': { 'address': '/eos/key/softkey_3', 'style': 'btn9', 'stylePressed': 'btn9Pressed', 'styleText': 'btn9Text', 'functype': 'btn', 'label': 'Softkey 3', 'argtype': 'i', 'argvalue': '0' },
    'softkey_4': { 'address': '/eos/key/softkey_4', 'style': 'btn9', 'stylePressed': 'btn9Pressed', 'styleText': 'btn9Text', 'functype': 'btn', 'label': 'SoftKey 4', 'argtype': 'i', 'argvalue': '0' },
    'softkey_5': { 'address': '/eos/key/softkey_5', 'style': 'btn9', 'stylePressed': 'btn9Pressed', 'styleText': 'btn9Text', 'functype': 'btn', 'label': 'Softkey 5', 'argtype': 'i', 'argvalue': '0' },
    'softkey_6': { 'address': '/eos/key/softkey_6', 'style': 'btn9', 'stylePressed': 'btn9Pressed', 'styleText': 'btn9Text', 'functype': 'btn', 'label': 'Softkey 6', 'argtype': 'i', 'argvalue': '0' },
    'sub': { 'address': '/eos/key/sub', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Sub', 'argtype': 'i', 'argvalue': '0' },
    'tab': { 'address': '/eos/key/tab', 'style': 'btn4', 'stylePressed': 'btn4Pressed', 'styleText': 'btn4Text', 'functype': 'btn', 'label': 'Tab', 'argtype': 'i', 'argvalue': '0' },
    'thru': { 'address': '/eos/key/thru', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': 'Thru', 'argtype': 'i', 'argvalue': '0' },
    'time': { 'address': '/eos/key/time', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Time', 'argtype': 'i', 'argvalue': '0' },
    'timing': { 'address': '/eos/key/timing', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Time', 'argtype': 'i', 'argvalue': '0' },
    'trace': { 'address': '/eos/key/trace', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Trace', 'argtype': 'i', 'argvalue': '0' },
    'track': { 'address': '/eos/key/track', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Q-Only Track', 'argtype': 'i', 'argvalue': '0' },
    'update': { 'address': '/eos/key/update', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Update', 'argtype': 'i', 'argvalue': '0' },
    'displays': { 'address': '/eos/key/displays', 'style': 'btn4', 'stylePressed': 'btn4Pressed', 'styleText': 'btn4Text', 'functype': 'btn', 'label': 'Displays', 'argtype': 'i', 'argvalue': '0' },
    'ping': { 'address': '/eos/key/displays', 'style': 'btn1', 'stylePressed': 'btn1Pressed', 'styleText': 'btn1Text', 'functype': 'btn', 'label': 'Ping', 'argtype': 'i', 'argvalue': '0' },
    'query': { 'address': '/eos/key/query', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': 'Query', 'argtype': 'i', 'argvalue': '0' },
    'undo': { 'address': '/eos/key/undo', 'style': 'btn1', 'stylePressed': 'btn1Pressed', 'styleText': 'btn1Text', 'functype': 'btn', 'label': 'UNDO', 'argtype': 'i', 'argvalue': '0' },
    'offset': { 'address': '/eos/key/offset', 'style': 'btn4', 'stylePressed': 'btn4Pressed', 'styleText': 'btn4Text', 'functype': 'btn', 'label': 'Offset', 'argtype': 'i', 'argvalue': '0' },
    'snapshot': { 'address': '/eos/key/snapshot', 'style': 'btn4', 'stylePressed': 'btn4Pressed', 'styleText': 'btn4Text', 'functype': 'btn', 'label': 'Snap', 'argtype': 'i', 'argvalue': '0' },
    'flexi': { 'address': '/eos/key/flexi', 'style': 'btn4', 'stylePressed': 'btn4Pressed', 'styleText': 'btn4Text', 'functype': 'btn', 'label': 'Flexi', 'argtype': 'i', 'argvalue': '0' },
    'intensity': { 'address': '/eos/key/intensity', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': 'Int', 'argtype': 'i', 'argvalue': '0' },
    'focus': { 'address': '/eos/key/focus', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': 'Focus', 'argtype': 'i', 'argvalue': '0' },
    'color': { 'address': '/eos/key/color', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': 'Color', 'argtype': 'i', 'argvalue': '0' },
    'beam': { 'address': '/eos/key/beam', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': 'Beam', 'argtype': 'i', 'argvalue': '0' },
    'all_nps': { 'address': '/eos/key/AllNPs', 'style': 'btn6', 'stylePressed': 'btn6Pressed', 'styleText': 'btn6Text', 'functype': 'btn', 'label': 'All NPs', 'argtype': 'i', 'argvalue': '0' },

    'ip': { 'address': '/eos/key/intensity_palette', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'IP', 'argtype': 'i', 'argvalue': '0' },
    'bp': { 'address': '/eos/key/beam_palette', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'BP', 'argtype': 'i', 'argvalue': '0' },
    'fp': { 'address': '/eos/key/focus_palette', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'FP', 'argtype': 'i', 'argvalue': '0' },
    'release': { 'address': '/eos/key/release', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Release', 'argtype': 'i', 'argvalue': '0' },
    'off': { 'address': '/eos/key/off', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'Off', 'argtype': 'i', 'argvalue': '0' },
    'stop_effect': { 'address': '/eos/key/stopeffect', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'StopFX', 'argtype': 'i', 'argvalue': '0' },

    'commandLine': { 'address': '', 'style': 'info3', 'stylePressed': 'info3Pressed', 'styleText': 'info3Text', 'functype': 'info', 'label': 'LIVE: CMD LINE', 'argtype': 'i', 'argvalue': '0' },
    'info_chan': { 'address': '', 'style': 'info1', 'stylePressed': 'info1Pressed', 'styleText': 'info1Text', 'functype': 'info', 'label': 'Chan : ', 'argtype': 'i', 'argvalue': '0' },
    'info_patch': { 'address': '', 'style': 'info1', 'stylePressed': 'info1Pressed', 'styleText': 'info1Text', 'functype': 'info', 'label': 'Patch : ', 'argtype': 'i', 'argvalue': '0' },
    'info_level': { 'address': '', 'style': 'info1', 'stylePressed': 'info1Pressed', 'styleText': 'info1Text', 'functype': 'info', 'label': 'Level : ', 'argtype': 'i', 'argvalue': '0' },
    'info_notes': { 'address': '', 'style': 'info1', 'stylePressed': 'info1Pressed', 'styleText': 'info1Text', 'functype': 'info', 'label': 'Notes : ', 'argtype': 'i', 'argvalue': '0' },

    'ds1_1': { 'address': '/eos/ds/1/1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_2': { 'address': '/eos/ds/1/2', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_3': { 'address': '/eos/ds/1/3', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_4': { 'address': '/eos/ds/1/4', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_5': { 'address': '/eos/ds/1/5', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_6': { 'address': '/eos/ds/1/6', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_7': { 'address': '/eos/ds/1/7', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_8': { 'address': '/eos/ds/1/8', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_9': { 'address': '/eos/ds/1/9', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_10': { 'address': '/eos/ds/1/10', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_11': { 'address': '/eos/ds/1/11', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_12': { 'address': '/eos/ds/1/12', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_13': { 'address': '/eos/ds/1/13', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_14': { 'address': '/eos/ds/1/14', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_15': { 'address': '/eos/ds/1/15', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_16': { 'address': '/eos/ds/1/16', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_17': { 'address': '/eos/ds/1/17', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_18': { 'address': '/eos/ds/1/18', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_19': { 'address': '/eos/ds/1/19', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_20': { 'address': '/eos/ds/1/20', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1_select': { 'address': '', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'select', 'label': 'SELECT', 'argtype': 's', 'argvalue': '1' },
    'ds1_up': { 'address': '/eos/ds/1/page/-1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': 'UP', 'argtype': 's', 'argvalue': '1' },
    'ds1_down': { 'address': '/eos/ds/1/page/1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': 'DOWN', 'argtype': 's', 'argvalue': '1' },
    'ds1_page': { 'address': '', 'style': 'btnlabel', 'stylePressed': 'label12Pressed', 'styleText': 'labeltext', 'functype': 'label', 'label': 'PAGE #', 'argtype': 's', 'argvalue': '' },
    'ds1_request': { 'address': 'eos/ds/1/group/1/20', 'style': 'label12', 'stylePressed': 'label12Pressed', 'styleText': 'btn12Text', 'functype': 'label', 'label': '', 'argtype': 's', 'argvalue': '' },


    'ds2_1': { 'address': '/eos/ds/2/1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_2': { 'address': '/eos/ds/2/2', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_3': { 'address': '/eos/ds/2/3', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_4': { 'address': '/eos/ds/2/4', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_5': { 'address': '/eos/ds/2/5', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_6': { 'address': '/eos/ds/2/6', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_7': { 'address': '/eos/ds/2/7', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_8': { 'address': '/eos/ds/2/8', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_9': { 'address': '/eos/ds/2/9', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_10': { 'address': '/eos/ds/2/10', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_11': { 'address': '/eos/ds/2/11', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_12': { 'address': '/eos/ds/2/12', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_13': { 'address': '/eos/ds/2/13', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_14': { 'address': '/eos/ds/2/14', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_15': { 'address': '/eos/ds/2/15', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_16': { 'address': '/eos/ds/2/16', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_17': { 'address': '/eos/ds/2/17', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_18': { 'address': '/eos/ds/2/18', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_19': { 'address': '/eos/ds/2/19', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_20': { 'address': '/eos/ds/2/20', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2_select': { 'address': '', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'select', 'label': 'SELECT', 'argtype': 's', 'argvalue': '1' },
    'ds2_up': { 'address': '/eos/ds/2/page/-1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': 'UP', 'argtype': 's', 'argvalue': '1' },
    'ds2_down': { 'address': '/eos/ds/2/page/1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': 'DOWN', 'argtype': 's', 'argvalue': '1' },
    'ds2_page': { 'address': '', 'style': 'label12', 'stylePressed': 'label12Pressed', 'styleText': 'labeltext', 'functype': 'label', 'label': 'PAGE #', 'argtype': 's', 'argvalue': '' },
    'ds2_request': { 'address': 'eos/ds/2/preset/1/20', 'style': 'label12', 'stylePressed': 'label12Pressed', 'styleText': 'btn12Text', 'functype': 'label', 'label': '', 'argtype': 's', 'argvalue': '' },

    'ds3_1': { 'address': '/eos/ds/3/1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_2': { 'address': '/eos/ds/3/2', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_3': { 'address': '/eos/ds/3/3', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_4': { 'address': '/eos/ds/3/4', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_5': { 'address': '/eos/ds/3/5', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_6': { 'address': '/eos/ds/3/6', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_7': { 'address': '/eos/ds/3/7', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_8': { 'address': '/eos/ds/3/8', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_9': { 'address': '/eos/ds/3/9', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_10': { 'address': '/eos/ds/3/10', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_11': { 'address': '/eos/ds/3/11', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_12': { 'address': '/eos/ds/3/12', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_13': { 'address': '/eos/ds/3/13', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_14': { 'address': '/eos/ds/3/14', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_15': { 'address': '/eos/ds/3/15', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_16': { 'address': '/eos/ds/3/16', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_17': { 'address': '/eos/ds/3/17', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_18': { 'address': '/eos/ds/3/18', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_19': { 'address': '/eos/ds/3/19', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_20': { 'address': '/eos/ds/3/20', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3_select': { 'address': '', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'select', 'label': 'SELECT', 'argtype': 's', 'argvalue': '1' },
    'ds3_up': { 'address': '/eos/ds/3/page/-1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': 'UP', 'argtype': 's', 'argvalue': '1' },
    'ds3_down': { 'address': '/eos/ds/3/page/1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': 'DOWN', 'argtype': 's', 'argvalue': '1' },
    'ds3_page': { 'address': '', 'style': 'label12', 'stylePressed': 'label12Pressed', 'styleText': 'labeltext', 'functype': 'label', 'label': 'PAGE #', 'argtype': 's', 'argvalue': '' },
    'ds3_request': { 'address': 'eos/ds/3/bp/1/20', 'style': 'label12', 'stylePressed': 'label12Pressed', 'styleText': 'btn12Text', 'functype': 'label', 'label': '', 'argtype': 's', 'argvalue': '' },

    'ds4_1': { 'address': '/eos/ds/4/1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_2': { 'address': '/eos/ds/4/2', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_3': { 'address': '/eos/ds/4/3', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_4': { 'address': '/eos/ds/4/4', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_5': { 'address': '/eos/ds/4/5', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_6': { 'address': '/eos/ds/4/6', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_7': { 'address': '/eos/ds/4/7', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_8': { 'address': '/eos/ds/4/8', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_9': { 'address': '/eos/ds/4/9', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_10': { 'address': '/eos/ds/4/10', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_11': { 'address': '/eos/ds/4/11', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_12': { 'address': '/eos/ds/4/12', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_13': { 'address': '/eos/ds/4/13', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_14': { 'address': '/eos/ds/4/14', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_15': { 'address': '/eos/ds/4/15', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_16': { 'address': '/eos/ds/4/16', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_17': { 'address': '/eos/ds/4/17', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_18': { 'address': '/eos/ds/4/18', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_19': { 'address': '/eos/ds/4/19', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_20': { 'address': '/eos/ds/4/20', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4_select': { 'address': '', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'select', 'label': 'SELECT', 'argtype': 's', 'argvalue': '1' },
    'ds4_up': { 'address': '/eos/ds/4/page/-1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': 'UP', 'argtype': 's', 'argvalue': '1' },
    'ds4_down': { 'address': '/eos/ds/4/page/1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': 'DOWN', 'argtype': 's', 'argvalue': '1' },
    'ds4_page': { 'address': '', 'style': 'label12', 'stylePressed': 'label12Pressed', 'styleText': 'labeltext', 'functype': 'label', 'label': 'PAGE #', 'argtype': 's', 'argvalue': '' },
    'ds4_request': { 'address': 'eos/ds/4/macro/1/20', 'style': 'label12', 'stylePressed': 'label12Pressed', 'styleText': 'btn12Text', 'functype': 'label', 'label': '', 'argtype': 's', 'argvalue': '' },

    'ds5_1': { 'address': '/eos/ds/5/1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5_2': { 'address': '/eos/ds/5/2', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5_3': { 'address': '/eos/ds/5/3', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5_4': { 'address': '/eos/ds/5/4', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5_5': { 'address': '/eos/ds/5/5', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5_6': { 'address': '/eos/ds/5/6', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5_7': { 'address': '/eos/ds/5/7', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5_8': { 'address': '/eos/ds/5/8', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5_9': { 'address': '/eos/ds/5/9', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5_10': { 'address': '/eos/ds/5/10', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5_select': { 'address': '', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'select', 'label': 'SELECT', 'argtype': 's', 'argvalue': '1' },
    'ds5_up': { 'address': '/eos/ds/5/page/-1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': 'UP', 'argtype': 's', 'argvalue': '1' },
    'ds5_down': { 'address': '/eos/ds/5/page/1', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': 'DOWN', 'argtype': 's', 'argvalue': '1' },
    'ds5_page': { 'address': '', 'style': 'label12', 'stylePressed': 'label12Pressed', 'styleText': 'labeltext', 'functype': 'label', 'label': 'PAGE #', 'argtype': 's', 'argvalue': '' },
    'ds5_request': { 'address': 'eos/ds/5/fx/1/10', 'style': 'label12', 'stylePressed': 'label12Pressed', 'styleText': 'btn12Text', 'functype': 'label', 'label': '', 'argtype': 's', 'argvalue': '' },

    'ds_Channels': { 'address': '/eos/ds/', 'style': 'btn5', 'stylePressed': 'dsselect5Pressed', 'styleText': 'dsselect5Text', 'functype': 'dsselect', 'label': 'Chan', 'argtype': 's', 'argvalue': '1' },
    'ds_Groups': { 'address': '/eos/ds/', 'style': 'btn6', 'stylePressed': 'dsselect6Pressed', 'styleText': 'dsselect6Text', 'functype': 'dsselect', 'label': 'Group', 'argtype': 's', 'argvalue': '1' },
    'ds_Intensity_Palettes': { 'address': '/eos/ds/', 'style': 'btn3', 'stylePressed': 'dsselect3Pressed', 'styleText': 'dsselect3Text', 'functype': 'dsselect', 'label': 'IP', 'argtype': 's', 'argvalue': '1' },
    'ds_Color_Palettes': { 'address': '/eos/ds/', 'style': 'btn12', 'stylePressed': 'dsselect12Pressed', 'styleText': 'dsselect12Text', 'functype': 'dsselect', 'label': 'CP', 'argtype': 's', 'argvalue': '1' },
    'ds_Focus_Palettes': { 'address': '/eos/ds/', 'style': 'btn4', 'stylePressed': 'dsselect4Pressed', 'styleText': 'dsselect4Text', 'functype': 'dsselect', 'label': 'FP', 'argtype': 's', 'argvalue': '1' },
    'ds_Beam_Palettes': { 'address': '/eos/ds/', 'style': 'btn8', 'stylePressed': 'dsselect8Pressed', 'styleText': 'dsselect8Text', 'functype': 'dsselect', 'label': 'BP', 'argtype': 's', 'argvalue': '1' },
    'ds_Presets': { 'address': '/eos/ds/', 'style': 'btn7', 'stylePressed': 'dsselect7Pressed', 'styleText': 'dsselect7Text', 'functype': 'dsselect', 'label': 'Preset', 'argtype': 's', 'argvalue': '1' },
    'ds_Effects': { 'address': '/eos/ds/', 'style': 'btn9', 'stylePressed': 'dsselect9Pressed', 'styleText': 'dsselect9Text', 'functype': 'dsselect', 'label': 'FX', 'argtype': 's', 'argvalue': '1' },
    'ds_Macros': { 'address': '/eos/ds/', 'style': 'btn11', 'stylePressed': 'dsselect11Pressed', 'styleText': 'dsselect11Text', 'functype': 'dsselect', 'label': 'Macro', 'argtype': 's', 'argvalue': '1' },
    'ds_Snapshots': { 'address': '/eos/ds/', 'style': 'btn1', 'stylePressed': 'dsselect1Pressed', 'styleText': 'dsselect1Text', 'functype': 'dsselect', 'label': 'Snap', 'argtype': 's', 'argvalue': '1' },
    'ds_Magic_Sheets': { 'address': '/eos/ds/', 'style': 'btn10', 'stylePressed': 'dsselect10Pressed', 'styleText': 'dsselect10Text', 'functype': 'dsselect', 'label': 'MS', 'argtype': 's', 'argvalue': '1' },
    'ds_Scenes': { 'address': '/eos/ds/', 'style': 'btn4', 'stylePressed': 'dsselect4Pressed', 'styleText': 'dsselect4Text', 'functype': 'dsselect', 'label': 'Scene', 'argtype': 's', 'argvalue': '1' },
    'ds_Flexi': { 'address': '/eos/ds/', 'style': 'btn12', 'stylePressed': 'dsselect12Pressed', 'styleText': 'dsselect12Text', 'functype': 'dsselect', 'label': 'Flexi Off', 'argtype': 's', 'argvalue': '1' },
    'ds_Clear': { 'address': '/eos/ds/', 'style': 'btn1', 'stylePressed': 'dsselect1Pressed', 'styleText': 'dsselect1Text', 'functype': 'dsselect', 'label': 'Clear', 'argtype': 's', 'argvalue': '1' },


    'colorStore': { 'address': '', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': 'STORE', 'argtype': '', 'argvalue': '' },






    'encoder1': { 'address': '/eoc/', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'ENCODER 1', 'argtype': 's', 'argvalue': '1' },
    'encoder2': { 'address': '/eoc/', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'ENCODER 2', 'argtype': 's', 'argvalue': '1' },
    'encoder3': { 'address': '/eoc/', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'ENCODER 3', 'argtype': 's', 'argvalue': '1' },
    'encoder4': { 'address': '/eoc/', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'ENCODER 4', 'argtype': 's', 'argvalue': '1' },
    'encoder5': { 'address': '/eoc/', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'ENCODER 5', 'argtype': 's', 'argvalue': '1' },
    'encoder6': { 'address': '/eoc/', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'ENCODER 6', 'argtype': 's', 'argvalue': '1' },
    'encoder7': { 'address': '/eoc/', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'ENCODER 7', 'argtype': 's', 'argvalue': '1' },
    'encoder8': { 'address': '/eoc/', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'ENCODER 8', 'argtype': 's', 'argvalue': '1' },
    'encoder9': { 'address': '/eoc/', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'ENCODER 9', 'argtype': 's', 'argvalue': '1' },
    'encoder10': { 'address': '/eoc/', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'ENCODER 10', 'argtype': 's', 'argvalue': '1' },
    'encoder11': { 'address': '/eoc/', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'ENCODER 11', 'argtype': 's', 'argvalue': '1' },
    'encoder12': { 'address': '/eoc/', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'ENCODER 12', 'argtype': 's', 'argvalue': '1' },


    'ds_lay_1': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '1', 'argtype': 's', 'argvalue': '1' },
    'ds_lay_2': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '2', 'argtype': 's', 'argvalue': '1' },
    'ds_lay_3': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '3', 'argtype': 's', 'argvalue': '1' },
    'ds_lay_4': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '4', 'argtype': 's', 'argvalue': '1' },
    'ds_lay_5': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '5', 'argtype': 's', 'argvalue': '1' },
    'ds_lay_6': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '6', 'argtype': 's', 'argvalue': '1' },
    'ds_lay_7': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '7', 'argtype': 's', 'argvalue': '1' },
    'ds_lay_8': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '8', 'argtype': 's', 'argvalue': '1' },
    'ds_lay_9': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '9', 'argtype': 's', 'argvalue': '1' },
    'ds_lay_10': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '10', 'argtype': 's', 'argvalue': '1' },

    'enc_lay_1': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '1', 'argtype': 's', 'argvalue': '1' },
    'enc_lay_2': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '2', 'argtype': 's', 'argvalue': '1' },
    'enc_lay_3': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '3', 'argtype': 's', 'argvalue': '1' },
    'enc_lay_4': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '4', 'argtype': 's', 'argvalue': '1' },
    'enc_lay_5': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '5', 'argtype': 's', 'argvalue': '1' },
    'enc_lay_6': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '6', 'argtype': 's', 'argvalue': '1' },
    'enc_lay_7': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '7', 'argtype': 's', 'argvalue': '1' },
    'enc_lay_8': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '8', 'argtype': 's', 'argvalue': '1' },
    'enc_lay_9': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '9', 'argtype': 's', 'argvalue': '1' },
    'enc_lay_10': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '10', 'argtype': 's', 'argvalue': '1' },

    'focus_lay_1': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '1', 'argtype': 's', 'argvalue': '1' },
    'focus_lay_2': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '2', 'argtype': 's', 'argvalue': '1' },
    'focus_lay_3': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '3', 'argtype': 's', 'argvalue': '1' },
    'focus_lay_4': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '4', 'argtype': 's', 'argvalue': '1' },
    'focus_lay_5': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '5', 'argtype': 's', 'argvalue': '1' },
    'focus_lay_6': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '6', 'argtype': 's', 'argvalue': '1' },
    'focus_lay_7': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '7', 'argtype': 's', 'argvalue': '1' },
    'focus_lay_8': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '8', 'argtype': 's', 'argvalue': '1' },
    'focus_lay_9': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '9', 'argtype': 's', 'argvalue': '1' },
    'focus_lay_10': { 'address': '/layout', 'style': 'btn12', 'stylePressed': 'btn12Pressed', 'styleText': 'btn12Text', 'functype': 'btn', 'label': '10', 'argtype': 's', 'argvalue': '1' },

    'fader1': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'PB 1', 'argtype': 's', 'argvalue': '1' },
    'fader1_go': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'GO 1', 'argtype': 's', 'argvalue': '1' },
    'fader1_back': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'STOP 1', 'argtype': 's', 'argvalue': '1' },
    'fader1_load': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'LOAD 1', 'argtype': 's', 'argvalue': '1' },
    'fader2': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'PB 2', 'argtype': 's', 'argvalue': '1' },
    'fader2_go': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'GO 2', 'argtype': 's', 'argvalue': '1' },
    'fader2_back': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'STOP 2', 'argtype': 's', 'argvalue': '1' },
    'fader2_load': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'LOAD 2', 'argtype': 's', 'argvalue': '1' },
    'fader3': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'PB 3', 'argtype': 's', 'argvalue': '1' },
    'fader3_go': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'GO 3', 'argtype': 's', 'argvalue': '1' },
    'fader3_back': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'STOP 3', 'argtype': 's', 'argvalue': '1' },
    'fader3_load': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'LOAD 3', 'argtype': 's', 'argvalue': '1' },
    'fader4': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'PB 4', 'argtype': 's', 'argvalue': '1' },
    'fader4_go': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'GO 4', 'argtype': 's', 'argvalue': '1' },
    'fader4_back': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'STOP 4', 'argtype': 's', 'argvalue': '1' },
    'fader4_load': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'LOAD 4', 'argtype': 's', 'argvalue': '1' },
    'fader5': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'PB 5', 'argtype': 's', 'argvalue': '1' },
    'fader5_go': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'GO 5', 'argtype': 's', 'argvalue': '1' },
    'fader5_back': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'STOP 5', 'argtype': 's', 'argvalue': '1' },
    'fader5_load': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'LOAD 5', 'argtype': 's', 'argvalue': '1' },
    'fader6': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'PB 6', 'argtype': 's', 'argvalue': '1' },
    'fader6_go': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'GO 6', 'argtype': 's', 'argvalue': '1' },
    'fader6_back': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'STOP 6', 'argtype': 's', 'argvalue': '1' },
    'fader6_load': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'LOAD 6', 'argtype': 's', 'argvalue': '1' },
    'fader7': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'PB 7', 'argtype': 's', 'argvalue': '1' },
    'fader7_go': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'GO 7', 'argtype': 's', 'argvalue': '1' },
    'fader7_back': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'STOP 7', 'argtype': 's', 'argvalue': '1' },
    'fader7_load': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'LOAD 7', 'argtype': 's', 'argvalue': '1' },
    'fader8': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'PB 8', 'argtype': 's', 'argvalue': '1' },
    'fader8_go': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'GO 8', 'argtype': 's', 'argvalue': '1' },
    'fader8_back': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'STOP 8', 'argtype': 's', 'argvalue': '1' },
    'fader8_load': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'LOAD 8', 'argtype': 's', 'argvalue': '1' },
    'fader9': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'PB 9', 'argtype': 's', 'argvalue': '1' },
    'fader9_go': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'GO 9', 'argtype': 's', 'argvalue': '1' },
    'fader9_back': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'STOP 9', 'argtype': 's', 'argvalue': '1' },
    'fader9_load': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'LOAD 9', 'argtype': 's', 'argvalue': '1' },
    'fader10': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'PB 10', 'argtype': 's', 'argvalue': '1' },
    'fader10_go': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'GO 10', 'argtype': 's', 'argvalue': '1' },
    'fader10_back': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'STOP 10', 'argtype': 's', 'argvalue': '1' },
    'fader10_load': { 'address': '/eos/fader', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'LOAD 10', 'argtype': 's', 'argvalue': '1' },
    'fader_up': { 'address': '/eos/fader/1/page/-1', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'UP', 'argtype': 's', 'argvalue': '1' },
    'fader_down': { 'address': '/eos/fader/1/page/1', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'DOWN', 'argtype': 's', 'argvalue': '1' },
    'fader_page': { 'address': '', 'style': 'label7', 'stylePressed': 'label7Pressed', 'styleText': 'label7Text', 'functype': 'label', 'label': 'PAGE #', 'argtype': 's', 'argvalue': '1' },
    
    'load': { 'address': '/eos/key/fader_ab', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'LOAD', 'argtype': 's', 'argvalue': '1' },
    'back_stop': { 'address': '/eos/key/stop', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'STOP ', 'argtype': 's', 'argvalue': '1' },
    'go': { 'address': '/eos/key/go_0', 'style': 'btn7', 'stylePressed': 'btn7Pressed', 'styleText': 'btn7Text', 'functype': 'btn', 'label': 'GO', 'argtype': 's', 'argvalue': '1' },
    'Qlist': { 'address': '/eos/load', 'style': 'btn11', 'stylePressed': 'btn11Pressed', 'styleText': 'btn11Text', 'functype': 'btn', 'label': 'QLIST', 'argtype': 's', 'argvalue': '1' },

    'encoder1_min': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder1_max': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder1_home': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder2_min': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder2_max': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder2_home': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder3_min': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder3_max': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder3_home': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder4_min': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder4_max': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder4_home': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder5_min': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder5_max': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder5_home': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder6_min': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder6_max': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder6_home': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder7_min': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder7_max': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder7_home': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder8_min': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder8_max': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder8_home': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder9_min': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder9_max': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder9_home': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder10_min': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder10_max': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder10_home': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder11_min': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder11_max': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder11_home': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder12_min': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder12_max': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder12_home': { 'address': '/eos/active/wheel/1', 'style': 'encoder_btn7', 'stylePressed': 'encoder_btn7Pressed', 'styleText': 'encoder_btn7Text', 'functype': 'encoder_btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },

    'oscLog': { 'address': '/eos/', 'style': 'oscLog', 'stylePressed': 'oscLogPressed', 'styleText': 'oscLogText', 'functype': 'oscLog', 'label': 'OSCLOG', 'argtype': 'i', 'argvalue': '1' },
    'showName': { 'address': '', 'style': 'showName', 'stylePressed': 'showNamePressed', 'styleText': 'showNameText', 'functype': 'showName', 'label': 'PLEASE CONNECT EOS', 'argtype': '', 'argvalue': '' },
};

export default buttonsAll;
