const buttons = {
    'colorStore': { 'address': '', 'style': 'btn-12', 'functype': 'btn', 'label': 'STORE', 'argtype': '', 'argvalue': '' },

    'encoderPageHeader': { 'address': 'encoderPage', 'style': 'pageHeader-7', 'functype': 'pageHeader', 'label': 'Encoders', 'argtype': 'i', 'argvalue': '0' },
    'dsPageHeader': { 'address': 'dsPage', 'style': 'pageHeader-7', 'functype': 'pageHeader', 'label': 'Direct Selects', 'argtype': 'i', 'argvalue': '0' },
    'faderPageHeader': { 'address': 'faderPage', 'style': 'pageHeader-7', 'functype': 'pageHeader', 'label': 'Playback', 'argtype': 'i', 'argvalue': '0' },
    'focusPageHeader': { 'address': 'focusPage', 'style': 'pageHeader-7', 'functype': 'pageHeader', 'label': 'Focus', 'argtype': 'i', 'argvalue': '0' },
    'remotePageHeader': { 'address': 'remotePage', 'style': 'pageHeader-7', 'functype': 'pageHeader', 'label': 'Remote', 'argtype': 'i', 'argvalue': '0' },
    'facepanelPageHeader': { 'address': 'facepanelPage', 'style': 'pageHeader-7', 'functype': 'pageHeader', 'label': 'Face Panel', 'argtype': 'i', 'argvalue': '0' },
    'testPageHeader': { 'address': 'testPage', 'style': 'pageHeader-7', 'functype': 'pageHeader', 'label': 'TEST', 'argtype': 'i', 'argvalue': '0' },

    'console': { 'address': '', 'style': 'console-7', 'functype': 'console', 'label': '', 'argtype': 'i', 'argvalue': '0' },
    'consoleInput': { 'address': '', 'style': 'consoleInput-7', 'functype': 'consoleInput', 'label': '', 'argtype': 'i', 'argvalue': '0' },
    'masterLayout': { 'address': '', 'style': 'masterLayout-7', 'functype': 'masterLayout', 'label': '', 'argtype': 'i', 'argvalue': '0' },
    'masterLayoutInput': { 'address': '', 'style': 'masterLayoutInput-7', 'functype': 'masterLayoutInput', 'label': '', 'argtype': 'i', 'argvalue': '0' },
    'layout': { 'address': '', 'style': 'layout-7', 'functype': 'layout', 'label': '', 'argtype': 'i', 'argvalue': '0' },
    'layoutBtn': { 'address': '', 'style': 'layoutBtn-7', 'functype': 'layoutBtn', 'label': '', 'argtype': 'i', 'argvalue': '0' },
    'minus': { 'address': '/eos/key/-', 'style': 'btn-6', 'functype': 'btn', 'label': '-', 'argtype': 'i', 'argvalue': '0' },
    'minus_percent': { 'address': '/eos/key/-%', 'style': 'btn-7', 'functype': 'btn', 'label': '-%', 'argtype': 'i', 'argvalue': '0' },
    'period': { 'address': '/eos/key/.', 'style': 'btn-6', 'functype': 'btn', 'label': '.', 'argtype': 'i', 'argvalue': '0' },
    'slash': { 'address': '/eos/key/\\', 'style': 'btn-7', 'functype': 'btn', 'label': '/', 'argtype': 'i', 'argvalue': '0' },
    'plus': { 'address': '/eos/key/+', 'style': 'btn-6', 'functype': 'btn', 'label': '+', 'argtype': 'i', 'argvalue': '0' },
    'plus_percent': { 'address': '/eos/key/+%', 'style': 'btn-7', 'functype': 'btn', 'label': '+%', 'argtype': 'i', 'argvalue': '0' },
    '0': { 'address': '/eos/key/0', 'style': 'btn-6', 'functype': 'btn', 'label': '0', 'argtype': 'i', 'argvalue': '0' },
    '1': { 'address': '/eos/key/1', 'style': 'btn-6', 'functype': 'btn', 'label': '1', 'argtype': 'i', 'argvalue': '0' },
    '2': { 'address': '/eos/key/2', 'style': 'btn-6', 'functype': 'btn', 'label': '2', 'argtype': 'i', 'argvalue': '0' },
    '3': { 'address': '/eos/key/3', 'style': 'btn-6', 'functype': 'btn', 'label': '3', 'argtype': 'i', 'argvalue': '0' },
    '4': { 'address': '/eos/key/4', 'style': 'btn-6', 'functype': 'btn', 'label': '4', 'argtype': 'i', 'argvalue': '0' },
    '5': { 'address': '/eos/key/5', 'style': 'btn-6', 'functype': 'btn', 'label': '5', 'argtype': 'i', 'argvalue': '0' },
    '6': { 'address': '/eos/key/6', 'style': 'btn-6', 'functype': 'btn', 'label': '6', 'argtype': 'i', 'argvalue': '0' },
    '7': { 'address': '/eos/key/7', 'style': 'btn-6', 'functype': 'btn', 'label': '7', 'argtype': 'i', 'argvalue': '0' },
    '8': { 'address': '/eos/key/8', 'style': 'btn-6', 'functype': 'btn', 'label': '8', 'argtype': 'i', 'argvalue': '0' },
    '9': { 'address': '/eos/key/9', 'style': 'btn-6', 'functype': 'btn', 'label': '9', 'argtype': 'i', 'argvalue': '0' },
    'about': { 'address': '/eos/key/about', 'style': 'btn-7', 'functype': 'btn', 'label': 'About', 'argtype': 'i', 'argvalue': '0' },
    'about': { 'address': '/eos/key/about', 'style': 'btn-7', 'functype': 'btn', 'label': 'About', 'argtype': 'i', 'argvalue': '0' },
    'activeChan': { 'address': '/eos/out/active/chan', 'style': 'info-7', 'functype': 'info', 'label': 'CHAN SELECTION', 'argtype': 'i', 'argvalue': '0' },
    'address': { 'address': '/eos/key/address', 'style': 'btn-7', 'functype': 'btn', 'label': 'Address Patch', 'argtype': 'i', 'argvalue': '0' },
    'Arrow_Down': { 'address': '/eos/key/Arrow_Down', 'style': 'btn-7', 'functype': 'btn', 'label': 'Down Arrow', 'argtype': 'i', 'argvalue': '0' },
    'Arrow_Left': { 'address': '/eos/key/Arrow_Left', 'style': 'btn-7', 'functype': 'btn', 'label': 'Left Arrow', 'argtype': 'i', 'argvalue': '0' },
    'Arrow_Right': { 'address': '/eos/key/Arrow_Right', 'style': 'btn-7', 'functype': 'btn', 'label': 'Right Arrow', 'argtype': 'i', 'argvalue': '0' },
    'Arrow_Up': { 'address': '/eos/key/Arrow_Up', 'style': 'btn-7', 'functype': 'btn', 'label': 'Up Arrow', 'argtype': 'i', 'argvalue': '0' },
    'assert': { 'address': '/eos/key/assert', 'style': 'btn-6', 'functype': 'btn', 'label': 'Assert', 'argtype': 'i', 'argvalue': '0' },
    'at': { 'address': '/eos/key/at', 'style': 'btn-7', 'functype': 'btn', 'label': 'At', 'argtype': 'i', 'argvalue': '0' },
    'beam_palette': { 'address': '/eos/key/beam_palette', 'style': 'btn-7', 'functype': 'btn', 'label': 'Beam Palette', 'argtype': 'i', 'argvalue': '0' },
    'Blind': { 'address': '/eos/key/Blind', 'style': 'btn-7', 'functype': 'btn', 'label': 'Blind', 'argtype': 'i', 'argvalue': '0' },
    'block': { 'address': '/eos/key/block', 'style': 'btn-6', 'functype': 'btn', 'label': 'Block', 'argtype': 'i', 'argvalue': '0' },
    'capture': { 'address': '/eos/key/capture', 'style': 'btn-2', 'functype': 'btn', 'label': 'Capture', 'argtype': 'i', 'argvalue': '0' },
    'check': { 'address': '/eos/key/check', 'style': 'btn-7', 'functype': 'btn', 'label': 'Check', 'argtype': 'i', 'argvalue': '0' },
    'clear_cmd': { 'address': '/eos/key/clear_cmd', 'style': 'btn-6', 'functype': 'btn', 'label': 'Clear', 'argtype': 'i', 'argvalue': '0' },
    'color_palette': { 'address': '/eos/key/color_palette', 'style': 'btn-7', 'functype': 'btn', 'label': 'Color Palette', 'argtype': 'i', 'argvalue': '0' },
    'copy_to': { 'address': '/eos/key/copy_to', 'style': 'btn-7', 'functype': 'btn', 'label': 'CopyTo', 'argtype': 'i', 'argvalue': '0' },
    'cue': { 'address': '/eos/key/cue', 'style': 'btn-7', 'functype': 'btn', 'label': 'Cue', 'argtype': 'i', 'argvalue': '0' },
    'data': { 'address': '/eos/key/data', 'style': 'btn-7', 'functype': 'btn', 'label': 'Data', 'argtype': 'i', 'argvalue': '0' },
    'delay': { 'address': '/eos/key/delay', 'style': 'btn-7', 'functype': 'btn', 'label': 'Delay', 'argtype': 'i', 'argvalue': '0' },
    'delete': { 'address': '/eos/key/delete', 'style': 'btn-7', 'functype': 'btn', 'label': 'Delete', 'argtype': 'i', 'argvalue': '0' },
    'effect': { 'address': '/eos/key/effect', 'style': 'btn-7', 'functype': 'btn', 'label': 'Effect', 'argtype': 'i', 'argvalue': '0' },
    'enter': { 'address': '/eos/key/enter', 'style': 'btn-7', 'functype': 'btn', 'label': 'Enter', 'argtype': 'i', 'argvalue': '0' },
    'Escape': { 'address': '/eos/key/Escape', 'style': 'btn-1', 'functype': 'btn', 'label': 'Escape', 'argtype': 'i', 'argvalue': '0' },
    'expand': { 'address': '/eos/key/expand', 'style': 'btn-7', 'functype': 'btn', 'label': 'Expand', 'argtype': 'i', 'argvalue': '0' },
    'fan': { 'address': '/eos/key/fan', 'style': 'btn-7', 'functype': 'btn', 'label': 'Fan', 'argtype': 'i', 'argvalue': '0' },
    'flash': { 'address': '/eos/key/flash', 'style': 'btn-7', 'functype': 'btn', 'label': 'Flash', 'argtype': 'i', 'argvalue': '0' },
    'flexichannel_mode': { 'address': '/eos/key/flexichannel_mode', 'style': 'btn-7', 'functype': 'btn', 'label': 'Flexi', 'argtype': 'i', 'argvalue': '0' },
    'focus_palette': { 'address': '/eos/key/focus_palette', 'style': 'btn-7', 'functype': 'btn', 'label': 'Focus Palette', 'argtype': 'i', 'argvalue': '0' },
    'format': { 'address': '/eos/key/format', 'style': 'btn-4', 'functype': 'btn', 'label': 'Format', 'argtype': 'i', 'argvalue': '0' },
    'full': { 'address': '/eos/key/full', 'style': 'btn-7', 'functype': 'btn', 'label': 'Full', 'argtype': 'i', 'argvalue': '0' },
    'go_to_cue': { 'address': '/eos/key/go_to_cue', 'style': 'btn-6', 'functype': 'btn', 'label': 'Goto Cue', 'argtype': 'i', 'argvalue': '0' },
    'group': { 'address': '/eos/key/group', 'style': 'btn-7', 'functype': 'btn', 'label': 'Group', 'argtype': 'i', 'argvalue': '0' },
    'help': { 'address': '/eos/key/help', 'style': 'btn-7', 'functype': 'btn', 'label': 'Help', 'argtype': 'i', 'argvalue': '0' },
    'highlight': { 'address': '/eos/key/highlight', 'style': 'btn-7', 'functype': 'btn', 'label': 'Highlight', 'argtype': 'i', 'argvalue': '0' },
    'home': { 'address': '/eos/key/home', 'style': 'btn-7', 'functype': 'btn', 'label': 'Home', 'argtype': 'i', 'argvalue': '0' },
    'intensity_palette': { 'address': '/eos/key/intensity_palette', 'style': 'btn-7', 'functype': 'btn', 'label': 'Int Palette', 'argtype': 'i', 'argvalue': '0' },
    'last': { 'address': '/eos/key/last', 'style': 'btn-2', 'functype': 'btn', 'label': 'Last', 'argtype': 'i', 'argvalue': '0' },
    'learn': { 'address': '/eos/key/learn', 'style': 'btn-7', 'functype': 'btn', 'label': 'Learn', 'argtype': 'i', 'argvalue': '0' },
    'level': { 'address': '/eos/key/level', 'style': 'btn-7', 'functype': 'btn', 'label': 'Level', 'argtype': 'i', 'argvalue': '0' },
    'Live': { 'address': '/eos/key/Live', 'style': 'btn-7', 'functype': 'btn', 'label': 'Live', 'argtype': 'i', 'argvalue': '0' },
    'macro': { 'address': '/eos/key/macro', 'style': 'btn-7', 'functype': 'btn', 'label': 'Macro', 'argtype': 'i', 'argvalue': '0' },
    'mark': { 'address': '/eos/key/mark', 'style': 'btn-7', 'functype': 'btn', 'label': 'Mark', 'argtype': 'i', 'argvalue': '0' },
    'more_softkeys': { 'address': '/eos/key/more_softkeys', 'style': 'btn-9', 'functype': 'btn', 'label': 'More Softkeys', 'argtype': 'i', 'argvalue': '0' },
    'next': { 'address': '/eos/key/next', 'style': 'btn-2', 'functype': 'btn', 'label': 'Next', 'argtype': 'i', 'argvalue': '0' },
    'out': { 'address': '/eos/key/out', 'style': 'btn-7', 'functype': 'btn', 'label': 'Out', 'argtype': 'i', 'argvalue': '0' },
    'park': { 'address': '/eos/key/park', 'style': 'btn-2', 'functype': 'btn', 'label': 'Park', 'argtype': 'i', 'argvalue': '0' },
    'part': { 'address': '/eos/key/part', 'style': 'btn-7', 'functype': 'btn', 'label': 'Part', 'argtype': 'i', 'argvalue': '0' },
    'path': { 'address': '/eos/key/path', 'style': 'btn-7', 'functype': 'btn', 'label': 'Path', 'argtype': 'i', 'argvalue': '0' },
    'preset': { 'address': '/eos/key/preset', 'style': 'btn-7', 'functype': 'btn', 'label': 'Preset', 'argtype': 'i', 'argvalue': '0' },
    'recall_from': { 'address': '/eos/key/recall_from', 'style': 'btn-6', 'functype': 'btn', 'label': 'Recall From', 'argtype': 'i', 'argvalue': '0' },
    'record': { 'address': '/eos/key/record', 'style': 'btn-7', 'functype': 'btn', 'label': 'Record', 'argtype': 'i', 'argvalue': '0' },
    'record_only': { 'address': '/eos/key/record_only', 'style': 'btn-7', 'functype': 'btn', 'label': 'Record Only', 'argtype': 'i', 'argvalue': '0' },
    'rem_dim': { 'address': '/eos/key/rem_dim', 'style': 'btn-7', 'functype': 'btn', 'label': 'Rem Dim', 'argtype': 'i', 'argvalue': '0' },
    'Select': { 'address': '/eos/key/Select', 'style': 'btn-1', 'functype': 'btn', 'label': 'Select', 'argtype': 'i', 'argvalue': '0' },
    'select_active': { 'address': '/eos/key/select_active', 'style': 'btn-2', 'functype': 'btn', 'label': 'Select Active', 'argtype': 'i', 'argvalue': '0' },
    'select_last': { 'address': '/eos/key/select_last', 'style': 'btn-2', 'functype': 'btn', 'label': 'Select Last', 'argtype': 'i', 'argvalue': '0' },
    'select_manual': { 'address': '/eos/key/select_manual', 'style': 'btn-2', 'functype': 'btn', 'label': 'Select Manual', 'argtype': 'i', 'argvalue': '0' },
    'shift': { 'address': '/eos/key/shift', 'style': 'btn-7', 'functype': 'btn', 'label': 'Shift', 'argtype': 'i', 'argvalue': '0' },
    'sneak': { 'address': '/eos/key/sneak', 'style': 'btn-7', 'functype': 'btn', 'label': 'Sneak', 'argtype': 'i', 'argvalue': '0' },
    'softkey_1': { 'address': '/eos/key/softkey_1', 'style': 'btn-9', 'functype': 'btn', 'label': 'SoftKey 1', 'argtype': 'i', 'argvalue': '0' },
    'softkey_2': { 'address': '/eos/key/softkey_2', 'style': 'btn-9', 'functype': 'btn', 'label': 'Softkey 2', 'argtype': 'i', 'argvalue': '0' },
    'softkey_3': { 'address': '/eos/key/softkey_3', 'style': 'btn-9', 'functype': 'btn', 'label': 'Softkey 3', 'argtype': 'i', 'argvalue': '0' },
    'softkey_4': { 'address': '/eos/key/softkey_4', 'style': 'btn-9', 'functype': 'btn', 'label': 'SoftKey 4', 'argtype': 'i', 'argvalue': '0' },
    'softkey_5': { 'address': '/eos/key/softkey_5', 'style': 'btn-9', 'functype': 'btn', 'label': 'Softkey 5', 'argtype': 'i', 'argvalue': '0' },
    'softkey_6': { 'address': '/eos/key/softkey_6', 'style': 'btn-9', 'functype': 'btn', 'label': 'Softkey 6', 'argtype': 'i', 'argvalue': '0' },
    'sub': { 'address': '/eos/key/sub', 'style': 'btn-7', 'functype': 'btn', 'label': 'Sub', 'argtype': 'i', 'argvalue': '0' },
    'tab': { 'address': '/eos/key/tab', 'style': 'btn-4', 'functype': 'btn', 'label': 'Tab', 'argtype': 'i', 'argvalue': '0' },
    'thru': { 'address': '/eos/key/thru', 'style': 'btn-6', 'functype': 'btn', 'label': 'Thru', 'argtype': 'i', 'argvalue': '0' },
    'time': { 'address': '/eos/key/time', 'style': 'btn-7', 'functype': 'btn', 'label': 'Time', 'argtype': 'i', 'argvalue': '0' },
    'timing': { 'address': '/eos/key/timing', 'style': 'btn-7', 'functype': 'btn', 'label': 'Time', 'argtype': 'i', 'argvalue': '0' },
    'trace': { 'address': '/eos/key/trace', 'style': 'btn-7', 'functype': 'btn', 'label': 'Trace', 'argtype': 'i', 'argvalue': '0' },
    'track': { 'address': '/eos/key/track', 'style': 'btn-7', 'functype': 'btn', 'label': 'Q-Only Track', 'argtype': 'i', 'argvalue': '0' },
    'update': { 'address': '/eos/key/update', 'style': 'btn-7', 'functype': 'btn', 'label': 'Update', 'argtype': 'i', 'argvalue': '0' },
    'displays': { 'address': '/eos/key/displays', 'style': 'btn-4', 'functype': 'btn', 'label': 'Displays', 'argtype': 'i', 'argvalue': '0' },
    'ping': { 'address': '/eos/key/displays', 'style': 'btn-1', 'functype': 'btn', 'label': 'Ping', 'argtype': 'i', 'argvalue': '0' },
    'query': { 'address': '/eos/key/query', 'style': 'btn-6', 'functype': 'btn', 'label': 'Query', 'argtype': 'i', 'argvalue': '0' },
    'undo': { 'address': '/eos/key/undo', 'style': 'btn-1', 'functype': 'btn', 'label': 'UNDO', 'argtype': 'i', 'argvalue': '0' },
    'offset': { 'address': '/eos/key/offset', 'style': 'btn-4', 'functype': 'btn', 'label': 'Offset', 'argtype': 'i', 'argvalue': '0' },
    'snapshot': { 'address': '/eos/key/snapshot', 'style': 'btn-4', 'functype': 'btn', 'label': 'Snap', 'argtype': 'i', 'argvalue': '0' },
    'flexi': { 'address': '/eos/key/flexi', 'style': 'btn-4', 'functype': 'btn', 'label': 'Flexi', 'argtype': 'i', 'argvalue': '0' },
    'intensity': { 'address': '/eos/key/intensity', 'style': 'btn-6', 'functype': 'btn', 'label': 'Int', 'argtype': 'i', 'argvalue': '0' },
    'focus': { 'address': '/eos/key/focus', 'style': 'btn-6', 'functype': 'btn', 'label': 'Focus', 'argtype': 'i', 'argvalue': '0' },
    'color': { 'address': '/eos/key/color', 'style': 'btn-6', 'functype': 'btn', 'label': 'Color', 'argtype': 'i', 'argvalue': '0' },
    'beam': { 'address': '/eos/key/beam', 'style': 'btn-6', 'functype': 'btn', 'label': 'Beam', 'argtype': 'i', 'argvalue': '0' },
    'all_nps': { 'address': '/eos/key/AllNPs', 'style': 'btn-6', 'functype': 'btn', 'label': 'All NPs', 'argtype': 'i', 'argvalue': '0' },

    'ip': { 'address': '/eos/key/intensity_palette', 'style': 'btn-7', 'functype': 'btn', 'label': 'IP', 'argtype': 'i', 'argvalue': '0' },
    'bp': { 'address': '/eos/key/beam_palette', 'style': 'btn-7', 'functype': 'btn', 'label': 'BP', 'argtype': 'i', 'argvalue': '0' },
    'fp': { 'address': '/eos/key/focus_palette', 'style': 'btn-7', 'functype': 'btn', 'label': 'FP', 'argtype': 'i', 'argvalue': '0' },
    'release': { 'address': '/eos/key/release', 'style': 'btn-7', 'functype': 'btn', 'label': 'Release', 'argtype': 'i', 'argvalue': '0' },
    'off': { 'address': '/eos/key/off', 'style': 'btn-7', 'functype': 'btn', 'label': 'Off', 'argtype': 'i', 'argvalue': '0' },
    'stop_effect': { 'address': '/eos/key/stopeffect', 'style': 'btn-7', 'functype': 'btn', 'label': 'StopFX', 'argtype': 'i', 'argvalue': '0' },

    'commandLine': { 'address': '', 'style': 'info-3', 'functype': 'info', 'label': 'LIVE: CMD LINE', 'argtype': 'i', 'argvalue': '0' },
    'info-chan': { 'address': '', 'style': 'info-1', 'functype': 'info', 'label': 'Chan : ', 'argtype': 'i', 'argvalue': '0' },
    'info-patch': { 'address': '', 'style': 'info-1', 'functype': 'info', 'label': 'Patch : ', 'argtype': 'i', 'argvalue': '0' },
    'info-level': { 'address': '', 'style': 'info-1', 'functype': 'info', 'label': 'Level : ', 'argtype': 'i', 'argvalue': '0' },
    'info-notes': { 'address': '', 'style': 'info-1', 'functype': 'info', 'label': 'Notes : ', 'argtype': 'i', 'argvalue': '0' },

    'ds1-1': { 'address': '/eos/ds/1/1', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-2': { 'address': '/eos/ds/1/2', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-3': { 'address': '/eos/ds/1/3', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-4': { 'address': '/eos/ds/1/4', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-5': { 'address': '/eos/ds/1/5', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-6': { 'address': '/eos/ds/1/6', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-7': { 'address': '/eos/ds/1/7', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-8': { 'address': '/eos/ds/1/8', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-9': { 'address': '/eos/ds/1/9', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-10': { 'address': '/eos/ds/1/10', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-11': { 'address': '/eos/ds/1/11', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-12': { 'address': '/eos/ds/1/12', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-13': { 'address': '/eos/ds/1/13', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-14': { 'address': '/eos/ds/1/14', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-15': { 'address': '/eos/ds/1/15', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-16': { 'address': '/eos/ds/1/16', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-17': { 'address': '/eos/ds/1/17', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-18': { 'address': '/eos/ds/1/18', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-19': { 'address': '/eos/ds/1/19', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-20': { 'address': '/eos/ds/1/20', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds1-select': { 'address': '', 'style': 'btn-12', 'functype': 'select', 'label': 'SELECT', 'argtype': 's', 'argvalue': '1' },
    'ds1-up': { 'address': '/eos/ds/1/page/-1', 'style': 'btn-12', 'functype': 'btn', 'label': 'UP', 'argtype': 's', 'argvalue': '1' },
    'ds1-down': { 'address': '/eos/ds/1/page/1', 'style': 'btn-12', 'functype': 'btn', 'label': 'DOWN', 'argtype': 's', 'argvalue': '1' },
    'ds1-page': { 'address': '', 'style': 'btn-none', 'functype': 'label', 'label': '', 'argtype': 's', 'argvalue': '' },

    'ds2-1': { 'address': '/eos/ds/2/1', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-2': { 'address': '/eos/ds/2/2', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-3': { 'address': '/eos/ds/2/3', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-4': { 'address': '/eos/ds/2/4', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-5': { 'address': '/eos/ds/2/5', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-6': { 'address': '/eos/ds/2/6', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-7': { 'address': '/eos/ds/2/7', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-8': { 'address': '/eos/ds/2/8', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-9': { 'address': '/eos/ds/2/9', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-10': { 'address': '/eos/ds/2/10', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-11': { 'address': '/eos/ds/2/11', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-12': { 'address': '/eos/ds/2/12', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-13': { 'address': '/eos/ds/2/13', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-14': { 'address': '/eos/ds/2/14', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-15': { 'address': '/eos/ds/2/15', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-16': { 'address': '/eos/ds/2/16', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-17': { 'address': '/eos/ds/2/17', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-18': { 'address': '/eos/ds/2/18', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-19': { 'address': '/eos/ds/2/19', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-20': { 'address': '/eos/ds/2/20', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds2-select': { 'address': '', 'style': 'btn-12', 'functype': 'select', 'label': 'SELECT', 'argtype': 's', 'argvalue': '1' },
    'ds2-up': { 'address': '/eos/ds/2/page/-1', 'style': 'btn-12', 'functype': 'btn', 'label': 'UP', 'argtype': 's', 'argvalue': '1' },
    'ds2-down': { 'address': '/eos/ds/2/page/1', 'style': 'btn-12', 'functype': 'btn', 'label': 'DOWN', 'argtype': 's', 'argvalue': '1' },
    'ds2-page': { 'address': '', 'style': 'btn-none', 'functype': 'label', 'label': '', 'argtype': 's', 'argvalue': '' },

    'ds3-1': { 'address': '/eos/ds/3/1', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-2': { 'address': '/eos/ds/3/2', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-3': { 'address': '/eos/ds/3/3', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-4': { 'address': '/eos/ds/3/4', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-5': { 'address': '/eos/ds/3/5', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-6': { 'address': '/eos/ds/3/6', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-7': { 'address': '/eos/ds/3/7', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-8': { 'address': '/eos/ds/3/8', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-9': { 'address': '/eos/ds/3/9', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-10': { 'address': '/eos/ds/3/10', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-11': { 'address': '/eos/ds/3/11', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-12': { 'address': '/eos/ds/3/12', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-13': { 'address': '/eos/ds/3/13', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-14': { 'address': '/eos/ds/3/14', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-15': { 'address': '/eos/ds/3/15', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-16': { 'address': '/eos/ds/3/16', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-17': { 'address': '/eos/ds/3/17', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-18': { 'address': '/eos/ds/3/18', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-19': { 'address': '/eos/ds/3/19', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-20': { 'address': '/eos/ds/3/20', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds3-select': { 'address': '', 'style': 'btn-12', 'functype': 'select', 'label': 'SELECT', 'argtype': 's', 'argvalue': '1' },
    'ds3-up': { 'address': '/eos/ds/3/page/-1', 'style': 'btn-12', 'functype': 'btn', 'label': 'UP', 'argtype': 's', 'argvalue': '1' },
    'ds3-down': { 'address': '/eos/ds/3/page/1', 'style': 'btn-12', 'functype': 'btn', 'label': 'DOWN', 'argtype': 's', 'argvalue': '1' },
    'ds3-page': { 'address': '', 'style': 'btn-none', 'functype': 'label', 'label': '', 'argtype': 's', 'argvalue': '' },

    'ds4-1': { 'address': '/eos/ds/4/1', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-2': { 'address': '/eos/ds/4/2', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-3': { 'address': '/eos/ds/4/3', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-4': { 'address': '/eos/ds/4/4', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-5': { 'address': '/eos/ds/4/5', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-6': { 'address': '/eos/ds/4/6', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-7': { 'address': '/eos/ds/4/7', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-8': { 'address': '/eos/ds/4/8', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-9': { 'address': '/eos/ds/4/9', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-10': { 'address': '/eos/ds/4/10', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-11': { 'address': '/eos/ds/4/11', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-12': { 'address': '/eos/ds/4/12', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-13': { 'address': '/eos/ds/4/13', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-14': { 'address': '/eos/ds/4/14', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-15': { 'address': '/eos/ds/4/15', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-16': { 'address': '/eos/ds/4/16', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-17': { 'address': '/eos/ds/4/17', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-18': { 'address': '/eos/ds/4/18', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-19': { 'address': '/eos/ds/4/19', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-20': { 'address': '/eos/ds/4/20', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds4-select': { 'address': '', 'style': 'btn-12', 'functype': 'select', 'label': 'SELECT', 'argtype': 's', 'argvalue': '1' },
    'ds4-up': { 'address': '/eos/ds/4/page/-1', 'style': 'btn-12', 'functype': 'btn', 'label': 'UP', 'argtype': 's', 'argvalue': '1' },
    'ds4-down': { 'address': '/eos/ds/4/page/1', 'style': 'btn-12', 'functype': 'btn', 'label': 'DOWN', 'argtype': 's', 'argvalue': '1' },
    'ds4-page': { 'address': '', 'style': 'btn-none', 'functype': 'label', 'label': '', 'argtype': 's', 'argvalue': '' },

    'ds5-1': { 'address': '/eos/ds/5/1', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5-2': { 'address': '/eos/ds/5/2', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5-3': { 'address': '/eos/ds/5/3', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5-4': { 'address': '/eos/ds/5/4', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5-5': { 'address': '/eos/ds/5/5', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5-6': { 'address': '/eos/ds/5/6', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5-7': { 'address': '/eos/ds/5/7', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5-8': { 'address': '/eos/ds/5/8', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5-9': { 'address': '/eos/ds/5/9', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5-10': { 'address': '/eos/ds/5/10', 'style': 'btn-12', 'functype': 'btn', 'label': '-', 'argtype': 's', 'argvalue': '1' },
    'ds5-select': { 'address': '', 'style': 'btn-12', 'functype': 'select', 'label': 'SELECT', 'argtype': 's', 'argvalue': '1' },
    'ds5-up': { 'address': '/eos/ds/5/page/-1', 'style': 'btn-12', 'functype': 'btn', 'label': 'UP', 'argtype': 's', 'argvalue': '1' },
    'ds5-down': { 'address': '/eos/ds/5/page/1', 'style': 'btn-12', 'functype': 'btn', 'label': 'DOWN', 'argtype': 's', 'argvalue': '1' },
    'ds5-page': { 'address': '', 'style': 'btn-none', 'functype': 'label', 'label': '', 'argtype': 's', 'argvalue': '' },


    'ds-Channels': { 'address': '/eos/ds/', 'style': 'btn-5', 'functype': 'ds-select', 'label': 'Chan', 'argtype': 's', 'argvalue': '1' },
    'ds-Groups': { 'address': '/eos/ds/', 'style': 'btn-6', 'functype': 'ds-select', 'label': 'Group', 'argtype': 's', 'argvalue': '1' },
    'ds-Intensity_Palettes': { 'address': '/eos/ds/', 'style': 'btn-3', 'functype': 'ds-select', 'label': 'IP', 'argtype': 's', 'argvalue': '1' },
    'ds-Color_Palettes': { 'address': '/eos/ds/', 'style': 'btn-12', 'functype': 'ds-select', 'label': 'CP', 'argtype': 's', 'argvalue': '1' },
    'ds-Focus_Palettes': { 'address': '/eos/ds/', 'style': 'btn-4', 'functype': 'ds-select', 'label': 'FP', 'argtype': 's', 'argvalue': '1' },
    'ds-Beam_Palettes': { 'address': '/eos/ds/', 'style': 'btn-8', 'functype': 'ds-select', 'label': 'BP', 'argtype': 's', 'argvalue': '1' },
    'ds-Presets': { 'address': '/eos/ds/', 'style': 'btn-7', 'functype': 'ds-select', 'label': 'Preset', 'argtype': 's', 'argvalue': '1' },
    'ds-Effects': { 'address': '/eos/ds/', 'style': 'btn-9', 'functype': 'ds-select', 'label': 'FX', 'argtype': 's', 'argvalue': '1' },
    'ds-Macros': { 'address': '/eos/ds/', 'style': 'btn-11', 'functype': 'ds-select', 'label': 'Macro', 'argtype': 's', 'argvalue': '1' },
    'ds-Snapshots': { 'address': '/eos/ds/', 'style': 'btn-1', 'functype': 'ds-select', 'label': 'Snap', 'argtype': 's', 'argvalue': '1' },
    'ds-Magic_Sheets': { 'address': '/eos/ds/', 'style': 'btn-10', 'functype': 'ds-select', 'label': 'MS', 'argtype': 's', 'argvalue': '1' },
    'ds-Scenes': { 'address': '/eos/ds/', 'style': 'btn-4', 'functype': 'ds-select', 'label': 'Scene', 'argtype': 's', 'argvalue': '1' },
    'ds-Flexi': { 'address': '/eos/ds/', 'style': 'btn-12', 'functype': 'ds-select', 'label': 'Flexi On', 'argtype': 's', 'argvalue': '1' },
    'ds-Clear': { 'address': '/eos/ds/', 'style': 'btn-1', 'functype': 'ds-select', 'label': 'Clear', 'argtype': 's', 'argvalue': '1' },

    'encoder1': { 'address': '/eoc/', 'style': 'btn-7', 'functype': 'btn', 'label': 'ENCODER 1', 'argtype': 's', 'argvalue': '1' },
    'encoder2': { 'address': '/eoc/', 'style': 'btn-7', 'functype': 'btn', 'label': 'ENCODER 2', 'argtype': 's', 'argvalue': '1' },
    'encoder3': { 'address': '/eoc/', 'style': 'btn-7', 'functype': 'btn', 'label': 'ENCODER 3', 'argtype': 's', 'argvalue': '1' },
    'encoder4': { 'address': '/eoc/', 'style': 'btn-7', 'functype': 'btn', 'label': 'ENCODER 4', 'argtype': 's', 'argvalue': '1' },
    'encoder5': { 'address': '/eoc/', 'style': 'btn-7', 'functype': 'btn', 'label': 'ENCODER 5', 'argtype': 's', 'argvalue': '1' },
    'encoder6': { 'address': '/eoc/', 'style': 'btn-7', 'functype': 'btn', 'label': 'ENCODER 6', 'argtype': 's', 'argvalue': '1' },
    'encoder7': { 'address': '/eoc/', 'style': 'btn-7', 'functype': 'btn', 'label': 'ENCODER 7', 'argtype': 's', 'argvalue': '1' },
    'encoder8': { 'address': '/eoc/', 'style': 'btn-7', 'functype': 'btn', 'label': 'ENCODER 8', 'argtype': 's', 'argvalue': '1' },
    'encoder9': { 'address': '/eoc/', 'style': 'btn-7', 'functype': 'btn', 'label': 'ENCODER 9', 'argtype': 's', 'argvalue': '1' },
    'encoder10': { 'address': '/eoc/', 'style': 'btn-7', 'functype': 'btn', 'label': 'ENCODER 10', 'argtype': 's', 'argvalue': '1' },
    'encoder11': { 'address': '/eoc/', 'style': 'btn-7', 'functype': 'btn', 'label': 'ENCODER 11', 'argtype': 's', 'argvalue': '1' },
    'encoder12': { 'address': '/eoc/', 'style': 'btn-7', 'functype': 'btn', 'label': 'ENCODER 12', 'argtype': 's', 'argvalue': '1' },

    'ds-lay-1': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '1', 'argtype': 's', 'argvalue': '1' },
    'ds-lay-2': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '2', 'argtype': 's', 'argvalue': '1' },
    'ds-lay-3': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '3', 'argtype': 's', 'argvalue': '1' },
    'ds-lay-4': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '4', 'argtype': 's', 'argvalue': '1' },
    'ds-lay-5': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '5', 'argtype': 's', 'argvalue': '1' },
    'ds-lay-6': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '6', 'argtype': 's', 'argvalue': '1' },
    'ds-lay-7': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '7', 'argtype': 's', 'argvalue': '1' },
    'ds-lay-8': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '8', 'argtype': 's', 'argvalue': '1' },
    'ds-lay-9': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '9', 'argtype': 's', 'argvalue': '1' },
    'ds-lay-10': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '10', 'argtype': 's', 'argvalue': '1' },

    'enc-lay-1': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '1', 'argtype': 's', 'argvalue': '1' },
    'enc-lay-2': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '2', 'argtype': 's', 'argvalue': '1' },
    'enc-lay-3': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '3', 'argtype': 's', 'argvalue': '1' },
    'enc-lay-4': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '4', 'argtype': 's', 'argvalue': '1' },
    'enc-lay-5': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '5', 'argtype': 's', 'argvalue': '1' },
    'enc-lay-6': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '6', 'argtype': 's', 'argvalue': '1' },
    'enc-lay-7': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '7', 'argtype': 's', 'argvalue': '1' },
    'enc-lay-8': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '8', 'argtype': 's', 'argvalue': '1' },
    'enc-lay-9': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '9', 'argtype': 's', 'argvalue': '1' },
    'enc-lay-10': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '10', 'argtype': 's', 'argvalue': '1' },

    'focus-lay-1': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '1', 'argtype': 's', 'argvalue': '1' },
    'focus-lay-2': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '2', 'argtype': 's', 'argvalue': '1' },
    'focus-lay-3': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '3', 'argtype': 's', 'argvalue': '1' },
    'focus-lay-4': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '4', 'argtype': 's', 'argvalue': '1' },
    'focus-lay-5': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '5', 'argtype': 's', 'argvalue': '1' },
    'focus-lay-6': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '6', 'argtype': 's', 'argvalue': '1' },
    'focus-lay-7': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '7', 'argtype': 's', 'argvalue': '1' },
    'focus-lay-8': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '8', 'argtype': 's', 'argvalue': '1' },
    'focus-lay-9': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '9', 'argtype': 's', 'argvalue': '1' },
    'focus-lay-10': { 'address': '/layout', 'style': 'btn-12', 'functype': 'btn', 'label': '10', 'argtype': 's', 'argvalue': '1' },

    'fader1': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'PB 1', 'argtype': 's', 'argvalue': '1' },
    'fader1-go': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'GO 1', 'argtype': 's', 'argvalue': '1' },
    'fader1-back': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'STOP 1', 'argtype': 's', 'argvalue': '1' },
    'fader1-load': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'LOAD 1', 'argtype': 's', 'argvalue': '1' },
    'fader2': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'PB 2', 'argtype': 's', 'argvalue': '1' },
    'fader2-go': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'GO 2', 'argtype': 's', 'argvalue': '1' },
    'fader2-back': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'STOP 2', 'argtype': 's', 'argvalue': '1' },
    'fader2-load': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'LOAD 2', 'argtype': 's', 'argvalue': '1' },
    'fader3': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'PB 3', 'argtype': 's', 'argvalue': '1' },
    'fader3-go': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'GO 3', 'argtype': 's', 'argvalue': '1' },
    'fader3-back': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'STOP 3', 'argtype': 's', 'argvalue': '1' },
    'fader3-load': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'LOAD 3', 'argtype': 's', 'argvalue': '1' },
    'fader4': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'PB 4', 'argtype': 's', 'argvalue': '1' },
    'fader4-go': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'GO 4', 'argtype': 's', 'argvalue': '1' },
    'fader4-back': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'STOP 4', 'argtype': 's', 'argvalue': '1' },
    'fader4-load': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'LOAD 4', 'argtype': 's', 'argvalue': '1' },
    'fader5': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'PB 5', 'argtype': 's', 'argvalue': '1' },
    'fader5-go': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'GO 5', 'argtype': 's', 'argvalue': '1' },
    'fader5-back': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'STOP 5', 'argtype': 's', 'argvalue': '1' },
    'fader5-load': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'LOAD 5', 'argtype': 's', 'argvalue': '1' },
    'fader6': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'PB 6', 'argtype': 's', 'argvalue': '1' },
    'fader6-go': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'GO 6', 'argtype': 's', 'argvalue': '1' },
    'fader6-back': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'STOP 6', 'argtype': 's', 'argvalue': '1' },
    'fader6-load': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'LOAD 6', 'argtype': 's', 'argvalue': '1' },
    'fader7': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'PB 7', 'argtype': 's', 'argvalue': '1' },
    'fader7-go': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'GO 7', 'argtype': 's', 'argvalue': '1' },
    'fader7-back': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'STOP 7', 'argtype': 's', 'argvalue': '1' },
    'fader7-load': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'LOAD 7', 'argtype': 's', 'argvalue': '1' },
    'fader8': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'PB 8', 'argtype': 's', 'argvalue': '1' },
    'fader8-go': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'GO 8', 'argtype': 's', 'argvalue': '1' },
    'fader8-back': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'STOP 8', 'argtype': 's', 'argvalue': '1' },
    'fader8-load': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'LOAD 8', 'argtype': 's', 'argvalue': '1' },
    'fader9': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'PB 9', 'argtype': 's', 'argvalue': '1' },
    'fader9-go': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'GO 9', 'argtype': 's', 'argvalue': '1' },
    'fader9-back': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'STOP 9', 'argtype': 's', 'argvalue': '1' },
    'fader9-load': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'LOAD 9', 'argtype': 's', 'argvalue': '1' },
    'fader10': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'PB 10', 'argtype': 's', 'argvalue': '1' },
    'fader10-go': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'GO 10', 'argtype': 's', 'argvalue': '1' },
    'fader10-back': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'STOP 10', 'argtype': 's', 'argvalue': '1' },
    'fader10-load': { 'address': '/eos/fader', 'style': 'btn-7', 'functype': 'btn', 'label': 'LOAD 10', 'argtype': 's', 'argvalue': '1' },
    'fader-up': { 'address': '/eos/fader/1/page/-1', 'style': 'btn-7', 'functype': 'btn', 'label': 'UP', 'argtype': 's', 'argvalue': '1' },
    'fader-down': { 'address': '/eos/fader/1/page/1', 'style': 'btn-7', 'functype': 'btn', 'label': 'DOWN', 'argtype': 's', 'argvalue': '1' },
    'fader-page': { 'address': '', 'style': 'btn-none', 'functype': 'label', 'label': 'PAGE #', 'argtype': 's', 'argvalue': '1' },

    'load': { 'address': '/eos/key/fader_ab', 'style': 'btn-7', 'functype': 'btn', 'label': 'LOAD', 'argtype': 's', 'argvalue': '1' },
    'back_stop': { 'address': '/eos/key/stop', 'style': 'btn-7', 'functype': 'btn', 'label': 'STOP ', 'argtype': 's', 'argvalue': '1' },
    'go': { 'address': '/eos/key/go_0', 'style': 'btn-7', 'functype': 'btn', 'label': 'GO', 'argtype': 's', 'argvalue': '1' },

    'Qlist': { 'address': '/eos/load', 'style': 'btn-11', 'functype': 'btn', 'label': 'QLIST', 'argtype': 's', 'argvalue': '1' },

    'encoder1-min': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder1-max': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder1-home': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder2-min': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder2-max': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder2-home': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder3-min': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder3-max': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder3-home': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder4-min': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder4-max': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder4-home': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder5-min': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder5-max': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder5-home': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder6-min': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder6-max': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder6-home': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder7-min': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder7-max': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder7-home': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder8-min': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder8-max': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder8-home': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder9-min': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder9-max': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder9-home': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder10-min': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder10-max': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder10-home': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder11-min': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder11-max': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder11-home': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },
    'encoder12-min': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MIN', 'argtype': 'i', 'argvalue': '1' },
    'encoder12-max': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'MAX', 'argtype': 'i', 'argvalue': '1' },
    'encoder12-home': { 'address': '/eos/active/wheel/1', 'style': 'encoder-btn-7', 'functype': 'encoder-btn', 'label': 'HOME', 'argtype': 'i', 'argvalue': '1' },

    '0_black': { 'address': '/eos/key/0', 'style': 'btn-11', 'functype': 'btn', 'label': '0', 'argtype': 'i', 'argvalue': '0' },
    '1_black': { 'address': '/eos/key/1', 'style': 'btn-11', 'functype': 'btn', 'label': '1', 'argtype': 'i', 'argvalue': '0' },
    '2_black': { 'address': '/eos/key/2', 'style': 'btn-11', 'functype': 'btn', 'label': '2', 'argtype': 'i', 'argvalue': '0' },
    '3_black': { 'address': '/eos/key/3', 'style': 'btn-11', 'functype': 'btn', 'label': '3', 'argtype': 'i', 'argvalue': '0' },
    '4_black': { 'address': '/eos/key/4', 'style': 'btn-11', 'functype': 'btn', 'label': '4', 'argtype': 'i', 'argvalue': '0' },
    '5_black': { 'address': '/eos/key/5', 'style': 'btn-11', 'functype': 'btn', 'label': '5', 'argtype': 'i', 'argvalue': '0' },
    '6_black': { 'address': '/eos/key/6', 'style': 'btn-11', 'functype': 'btn', 'label': '6', 'argtype': 'i', 'argvalue': '0' },
    '7_black': { 'address': '/eos/key/7', 'style': 'btn-11', 'functype': 'btn', 'label': '7', 'argtype': 'i', 'argvalue': '0' },
    '8_black': { 'address': '/eos/key/8', 'style': 'btn-11', 'functype': 'btn', 'label': '8', 'argtype': 'i', 'argvalue': '0' },
    '9_black': { 'address': '/eos/key/9', 'style': 'btn-11', 'functype': 'btn', 'label': '9', 'argtype': 'i', 'argvalue': '0' },
    'minus_black': { 'address': '/eos/key/-', 'style': 'btn-11', 'functype': 'btn', 'label': '-', 'argtype': 'i', 'argvalue': '0' },
    'plus_black': { 'address': '/eos/key/+', 'style': 'btn-11', 'functype': 'btn', 'label': '+', 'argtype': 'i', 'argvalue': '0' },
    'period_black': { 'address': '/eos/key/.', 'style': 'btn-11', 'functype': 'btn', 'label': '.', 'argtype': 'i', 'argvalue': '0' },
    'clear_cmd_black': { 'address': '/eos/key/clear_cmd', 'style': 'btn-11', 'functype': 'btn', 'label': 'Clear', 'argtype': 'i', 'argvalue': '0' },
    'slash_black': { 'address': '/eos/key/\\', 'style': 'btn-11', 'functype': 'btn', 'label': '/', 'argtype': 'i', 'argvalue': '0' },
    'level_black': { 'address': '/eos/key/level', 'style': 'btn-11', 'functype': 'btn', 'label': 'Level', 'argtype': 'i', 'argvalue': '0' },
    'enter_black': { 'address': '/eos/key/enter', 'style': 'btn-11', 'functype': 'btn', 'label': 'Enter', 'argtype': 'i', 'argvalue': '0' },
    'at_black': { 'address': '/eos/key/at', 'style': 'btn-11', 'functype': 'btn', 'label': 'At', 'argtype': 'i', 'argvalue': '0' },
    'full_black': { 'address': '/eos/key/full', 'style': 'btn-11', 'functype': 'btn', 'label': 'Full', 'argtype': 'i', 'argvalue': '0' },
    'sneak_black': { 'address': '/eos/key/sneak', 'style': 'btn-11', 'functype': 'btn', 'label': 'Sneak', 'argtype': 'i', 'argvalue': '0' },
    'thru_black': { 'address': '/eos/key/thru', 'style': 'btn-11', 'functype': 'btn', 'label': 'Thru', 'argtype': 'i', 'argvalue': '0' }
};// JavaScript source code
